apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project-1
  namespace: argocd
spec:
  description: Project 1 for Group 9
  sourceRepos:
    - '*'    # Cho phép lấy code từ mọi repo (hoặc bạn có thể giới hạn)
  destinations:
    - namespace: default
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'

